version: "3"
services: 
  postgresql2:
    image: postgres:13
    container_name: 'postgresql_solicitudes'
    restart: always
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=eliascolon98
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/data/postgresql2
    ports: 
      - 5432:5432
  appbackend_nest:
    build:
      context: ./
      dockerfile: Dockerfile
    image: node
    container_name: 'appbackendsolicitudNest'
    environment: 
      - BD_DRIVE=postgres
      - BD_PORT=5432'
      - BD_NAME=postgres
      - BD_USERNAME=postgres
      - DB_HOST=postgresql2
      - BD_PASSWORD=eliascolon98
    restart: always
    ports:
      - "3000:3000"
    depends_on: 
      - postgresql2
volumes:
  pgdata:
    driver: local